/* eslint-disable @typescript-eslint/no-explicit-any */
import { notFound } from "next/navigation";
import { getInvoice } from "@/lib/documents/queries";
function dateText(value: unknown) { return value instanceof Date ? value.toISOString().slice(0, 10) : value ? String(value).slice(0, 10) : ""; }

export default async function InvoicePrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const data = await getInvoice(id); if (!data) notFound();
  const { invoice, lines } = data; const documentDate = dateText(invoice.document_date); const dueDate = dateText(invoice.due_date); const seller = data.company ?? invoice.seller_snapshot;
  return <main className="invoice-print mx-auto min-h-[297mm] w-[210mm] bg-white p-[15mm] text-slate-900 print:mx-0 print:min-h-0 print:w-[210mm] print:p-[15mm]">
    <div className="mb-8 flex justify-between border-b-2 border-slate-900 pb-5"><div><div className="text-xl font-bold">{seller.legal_name}</div><div>{seller.address || "-"}</div><div>เลขประจำตัวผู้เสียภาษี: {seller.tax_id || "-"}</div><div className="text-sm">โทร. {seller.phone || "-"} · {seller.email || "-"}</div></div><div className="text-right text-sm"><h1 className="text-2xl font-bold">{invoice.document_title}</h1><p className="mt-1">เลขที่ {invoice.invoice_no}</p><div>วันที่ {documentDate}</div><div>ครบกำหนด {dueDate || "-"}</div></div></div>
    <div className="mb-8 text-sm"><div className="font-semibold">ลูกค้า</div><div>{invoice.customer_snapshot.legal_name}</div><div>{invoice.customer_snapshot.address}</div></div>
    <table className="w-full border-collapse text-sm"><thead><tr><th className="border-b border-slate-300 p-2 text-left">รายการ</th><th className="border-b border-slate-300 p-2 text-right">จำนวน</th><th className="border-b border-slate-300 p-2 text-right">ราคา/หน่วย</th><th className="border-b border-slate-300 p-2 text-right">รวม</th></tr></thead><tbody>{lines.map((line: any) => <tr key={line.id}><td className="border-b border-slate-200 p-2">{line.name_snapshot}</td><td className="border-b border-slate-200 p-2 text-right">{line.quantity}</td><td className="border-b border-slate-200 p-2 text-right">{Number(line.unit_price_ex_vat).toLocaleString("th-TH", { minimumFractionDigits: 2 })}</td><td className="border-b border-slate-200 p-2 text-right">{Number(line.total_amount).toLocaleString("th-TH", { minimumFractionDigits: 2 })}</td></tr>)}</tbody></table>
    <div className="mt-8 ml-auto w-64 space-y-2 text-right text-sm"><div>VAT {Number(invoice.vat_amount).toLocaleString("th-TH", { minimumFractionDigits: 2 })}</div><div>หัก ณ ที่จ่าย ({Number(invoice.wht_rate ?? 0)}%) -{Number(invoice.estimated_wht_amount ?? 0).toLocaleString("th-TH", { minimumFractionDigits: 2 })}</div><div className="border-t border-slate-900 pt-2 text-lg font-bold">ยอดสุทธิรับ {Number(invoice.estimated_receivable ?? invoice.grand_total).toLocaleString("th-TH", { minimumFractionDigits: 2 })} บาท</div></div>
    <div className="mt-10 rounded bg-slate-50 p-3 text-sm"><b>ชำระเงินเข้าบัญชี:</b> {seller.bank_name || "-"} สาขา {seller.bank_branch || "-"} เลขที่บัญชี {seller.bank_account_no || "-"}</div><p className="mt-8 text-center text-xs text-slate-500">เอกสารนี้เป็น{invoice.document_title}ตามขอบเขตระบบรุ่นแรก ยังไม่ใช่ใบกำกับภาษีหรือหลักฐานรับชำระเงิน</p>
  </main>;
}
